name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has not been updated for a while and will be closed in 2 weeks. If it is still relevant, reply or remove the stale tag.'
          stale-pr-message: 'This pull request has not been updated for a while and will be closed in 2 weeks. If it is still relevant, reply or remove the stale tag.'
          close-issue-message: 'This issue has automatically been closed due to lack of recent activity.'
          close-pr-message: 'This pull request has automatically been closed due to lack of recent activity.'
          days-before-stale: 90
          days-before-close: 14
